### ISSUE TITLE
Build fails when certbot depends on acme features not yet released into PyPI

### ISSUE THREAD

**Issue by basak** [basak/certbot-snap-build#12]
Details at: https://forum.snapcraft.io/t/building-a-snap-with-a-multi-python-project/12284

**Comment by basak** [comment]
This affects only edge since this situation will never arise on builds of released versions of certbot.

**Comment by basak** [comment]
Sergio suggested something like this as a workaround:
```
parts:
    p:
        source: certbot.git
        plugin: python
        python-packages:
        - http://dependency.git
```

We can give this a try when the situation next arises.
